### ISSUE TITLE
Confusion about the optical flow estimation

### ISSUE THREAD

**Issue by KK-xi** [uzh-rpg/rpg_event_representation_learning#7]
Hi！Thanks for your sharing. There was a problem when I was doing the optical flow estimation experiment, that is, an out-of-range  occurred at the code :
vox.put_(idx.long(), values, accumulate=True)
I checked this issue and found that it was a problem with the sample I generated from MVSEC dataset. I aggregated the events of the left and right event cameras, and extracted the events every 20ms as a sample. Is this what your article describes? How is the correct sample generated? 
Looking forward to your reply! Thanks!

**Comment by zeqiong-06** [comment]
Hi, have you solved the problem now? I also meet this issue. Could you explain it to me? Thanks.
